---
- name: Testing andrewrothstein.om
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'om --version'
      ansible.builtin.command: om --version
      changed_when: false
      register: om_test_output
    - name: Output from 'om --version'
      ansible.builtin.debug:
        msg: '{{ om_test_output.stdout }}'
