---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/om --version
    register: om_test_output
  - name: om --version
    debug:
      msg: '{{ om_test_output.stdout }}'
