---
- include_role:
    name: andrewrothstein.unarchive-deps
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for installation at {{ om_exe }}
  become: true
  stat:
    path: '{{ om_exe }}'
  changed_when: false
  register: om_binary
- when: not om_binary.stat.exists
  block:
    - name: download {{ om_url }} to {{ om_tmp_archive }}...
      become: true
      become_user: root
      get_url:
        url: '{{ om_url }}'
        dest: '{{ om_tmp_archive }}'
        checksum: '{{ om_checksum }}'
        mode: 0644
    - name: mkdir {{ om_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ om_install_dir }}'
        state: directory
        mode: 0755
    - name: unarchive {{ om_tmp_archive }} to {{ om_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ om_tmp_archive }}'
        dest: '{{ om_install_dir }}'
        creates: '{{ om_exe }}'
  always:
    - name: rm {{ om_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ om_tmp_archive }}'
        state: absent
- name: linking {{ om_link }} to {{ om_exe }}...
  become: true
  become_user: root
  file:
    src: '{{ om_exe }}'
    dest: '{{ om_link }}'
    state: link
