---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for installation at {{ om_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ om_exe }}'
  changed_when: false
  register: om_binary
- name: Downloading and installing om
  when: not om_binary.stat.exists
  block:
    - name: Download {{ om_url }} to {{ om_tmp_archive }}...
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ om_url }}'
        dest: '{{ om_tmp_archive }}'
        checksum: '{{ om_checksum }}'
        mode: '644'
    - name: Mkdir {{ om_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ om_install_dir }}'
        state: directory
        mode: '755'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ om_tmp_archive }} to {{ om_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ om_tmp_archive }}'
        dest: '{{ om_install_dir }}'
        creates: '{{ om_exe }}'
  always:
    - name: Rm {{ om_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ om_tmp_archive }}'
        state: absent
- name: Linking {{ om_link }} to {{ om_exe }}...
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ om_exe }}'
    dest: '{{ om_link }}'
    state: link
